# Generated by gallery/generate.py; do not edit.
function bigreactors_gallery:clear
# basic-shell-164-100-164: basic assembled turbine shell
setblock 164 100 164 bigreactors:basic_turbinecasing
# basic-shell-164-100-165: basic assembled turbine shell
setblock 164 100 165 bigreactors:basic_turbinecasing
# basic-shell-164-100-166: basic assembled turbine shell
setblock 164 100 166 bigreactors:basic_turbinecasing
# basic-shell-164-100-167: basic assembled turbine shell
setblock 164 100 167 bigreactors:basic_turbinecasing
# basic-shell-164-100-168: basic assembled turbine shell
setblock 164 100 168 bigreactors:basic_turbinecasing
# basic-shell-164-101-164: basic assembled turbine shell
setblock 164 101 164 bigreactors:basic_turbinecasing
# basic-shell-164-101-165: basic assembled turbine shell
setblock 164 101 165 bigreactors:basic_turbinecasing
# basic-shell-164-101-166: basic assembled turbine shell
setblock 164 101 166 bigreactors:basic_turbinecasing
# basic-shell-164-101-167: basic assembled turbine shell
setblock 164 101 167 bigreactors:basic_turbinecasing
# basic-shell-164-101-168: basic assembled turbine shell
setblock 164 101 168 bigreactors:basic_turbinecasing
# basic-shell-164-102-164: basic assembled turbine shell
setblock 164 102 164 bigreactors:basic_turbinecasing
# basic-shell-164-102-165: basic assembled turbine shell
setblock 164 102 165 bigreactors:basic_turbinecasing
# basic-shell-164-102-166: basic assembled turbine shell
setblock 164 102 166 bigreactors:basic_turbinecasing
# basic-shell-164-102-167: basic assembled turbine shell
setblock 164 102 167 bigreactors:basic_turbinecasing
# basic-shell-164-102-168: basic assembled turbine shell
setblock 164 102 168 bigreactors:basic_turbinecasing
# basic-shell-164-103-164: basic assembled turbine shell
setblock 164 103 164 bigreactors:basic_turbinecasing
# basic-shell-164-103-165: basic assembled turbine shell
setblock 164 103 165 bigreactors:basic_turbinecasing
# basic-shell-164-103-166: basic assembled turbine shell
setblock 164 103 166 bigreactors:basic_turbinecasing
# basic-shell-164-103-167: basic assembled turbine shell
setblock 164 103 167 bigreactors:basic_turbinecasing
# basic-shell-164-103-168: basic assembled turbine shell
setblock 164 103 168 bigreactors:basic_turbinecasing
# basic-shell-164-104-164: basic assembled turbine shell
setblock 164 104 164 bigreactors:basic_turbinecasing
# basic-shell-164-104-165: basic assembled turbine shell
setblock 164 104 165 bigreactors:basic_turbinecasing
# basic-shell-164-104-166: basic assembled turbine shell
setblock 164 104 166 bigreactors:basic_turbinecasing
# basic-shell-164-104-167: basic assembled turbine shell
setblock 164 104 167 bigreactors:basic_turbinecasing
# basic-shell-164-104-168: basic assembled turbine shell
setblock 164 104 168 bigreactors:basic_turbinecasing
# basic-shell-165-100-164: basic assembled turbine shell
setblock 165 100 164 bigreactors:basic_turbinecasing
# basic-shell-165-100-165: basic assembled turbine shell
setblock 165 100 165 bigreactors:basic_turbinecasing
# basic-shell-165-100-166: basic assembled turbine shell
setblock 165 100 166 bigreactors:basic_turbinecasing
# basic-shell-165-100-167: basic assembled turbine shell
setblock 165 100 167 bigreactors:basic_turbinecasing
# basic-shell-165-100-168: basic assembled turbine shell
setblock 165 100 168 bigreactors:basic_turbinecasing
# basic-shell-165-101-164: basic assembled turbine shell
setblock 165 101 164 bigreactors:basic_turbinecasing
# basic-shell-165-103-164: basic assembled turbine shell
setblock 165 103 164 bigreactors:basic_turbinecasing
# basic-shell-165-104-164: basic assembled turbine shell
setblock 165 104 164 bigreactors:basic_turbinecasing
# basic-shell-165-104-168: basic assembled turbine shell
setblock 165 104 168 bigreactors:basic_turbinecasing
# basic-shell-166-100-164: basic assembled turbine shell
setblock 166 100 164 bigreactors:basic_turbinecasing
# basic-shell-166-100-165: basic assembled turbine shell
setblock 166 100 165 bigreactors:basic_turbinecasing
# basic-shell-166-100-166: basic assembled turbine shell
setblock 166 100 166 bigreactors:basic_turbinecasing
# basic-shell-166-100-167: basic assembled turbine shell
setblock 166 100 167 bigreactors:basic_turbinecasing
# basic-shell-166-100-168: basic assembled turbine shell
setblock 166 100 168 bigreactors:basic_turbinecasing
# basic-shell-166-101-164: basic assembled turbine shell
setblock 166 101 164 bigreactors:basic_turbinecasing
# basic-shell-166-103-164: basic assembled turbine shell
setblock 166 103 164 bigreactors:basic_turbinecasing
# basic-shell-166-104-164: basic assembled turbine shell
setblock 166 104 164 bigreactors:basic_turbinecasing
# basic-shell-166-104-168: basic assembled turbine shell
setblock 166 104 168 bigreactors:basic_turbinecasing
# basic-shell-167-100-164: basic assembled turbine shell
setblock 167 100 164 bigreactors:basic_turbinecasing
# basic-shell-167-100-165: basic assembled turbine shell
setblock 167 100 165 bigreactors:basic_turbinecasing
# basic-shell-167-100-166: basic assembled turbine shell
setblock 167 100 166 bigreactors:basic_turbinecasing
# basic-shell-167-100-167: basic assembled turbine shell
setblock 167 100 167 bigreactors:basic_turbinecasing
# basic-shell-167-100-168: basic assembled turbine shell
setblock 167 100 168 bigreactors:basic_turbinecasing
# basic-shell-167-101-164: basic assembled turbine shell
setblock 167 101 164 bigreactors:basic_turbinecasing
# basic-shell-167-102-164: basic assembled turbine shell
setblock 167 102 164 bigreactors:basic_turbinecasing
# basic-shell-167-103-164: basic assembled turbine shell
setblock 167 103 164 bigreactors:basic_turbinecasing
# basic-shell-167-104-164: basic assembled turbine shell
setblock 167 104 164 bigreactors:basic_turbinecasing
# basic-shell-167-104-168: basic assembled turbine shell
setblock 167 104 168 bigreactors:basic_turbinecasing
# basic-shell-168-100-164: basic assembled turbine shell
setblock 168 100 164 bigreactors:basic_turbinecasing
# basic-shell-168-100-165: basic assembled turbine shell
setblock 168 100 165 bigreactors:basic_turbinecasing
# basic-shell-168-100-166: basic assembled turbine shell
setblock 168 100 166 bigreactors:basic_turbinecasing
# basic-shell-168-100-167: basic assembled turbine shell
setblock 168 100 167 bigreactors:basic_turbinecasing
# basic-shell-168-100-168: basic assembled turbine shell
setblock 168 100 168 bigreactors:basic_turbinecasing
# basic-shell-168-101-164: basic assembled turbine shell
setblock 168 101 164 bigreactors:basic_turbinecasing
# basic-shell-168-101-168: basic assembled turbine shell
setblock 168 101 168 bigreactors:basic_turbinecasing
# basic-shell-168-102-164: basic assembled turbine shell
setblock 168 102 164 bigreactors:basic_turbinecasing
# basic-shell-168-102-168: basic assembled turbine shell
setblock 168 102 168 bigreactors:basic_turbinecasing
# basic-shell-168-103-164: basic assembled turbine shell
setblock 168 103 164 bigreactors:basic_turbinecasing
# basic-shell-168-103-168: basic assembled turbine shell
setblock 168 103 168 bigreactors:basic_turbinecasing
# basic-shell-168-104-164: basic assembled turbine shell
setblock 168 104 164 bigreactors:basic_turbinecasing
# basic-shell-168-104-165: basic assembled turbine shell
setblock 168 104 165 bigreactors:basic_turbinecasing
# basic-shell-168-104-166: basic assembled turbine shell
setblock 168 104 166 bigreactors:basic_turbinecasing
# basic-shell-168-104-167: basic assembled turbine shell
setblock 168 104 167 bigreactors:basic_turbinecasing
# basic-shell-168-104-168: basic assembled turbine shell
setblock 168 104 168 bigreactors:basic_turbinecasing
# basic-top-glass-165-165: basic assembled turbine glass
setblock 165 104 165 bigreactors:basic_turbineglass
# basic-top-glass-165-166: basic assembled turbine glass
setblock 165 104 166 bigreactors:basic_turbineglass
# basic-top-glass-165-167: basic assembled turbine glass
setblock 165 104 167 bigreactors:basic_turbineglass
# basic-top-glass-166-165: basic assembled turbine glass
setblock 166 104 165 bigreactors:basic_turbineglass
# basic-top-glass-166-166: basic assembled turbine glass
setblock 166 104 166 bigreactors:basic_turbineglass
# basic-top-glass-166-167: basic assembled turbine glass
setblock 166 104 167 bigreactors:basic_turbineglass
# basic-top-glass-167-165: basic assembled turbine glass
setblock 167 104 165 bigreactors:basic_turbineglass
# basic-top-glass-167-166: basic assembled turbine glass
setblock 167 104 166 bigreactors:basic_turbineglass
# basic-top-glass-167-167: basic assembled turbine glass
setblock 167 104 167 bigreactors:basic_turbineglass
# basic-side-glass-101-165: basic assembled turbine glass
setblock 168 101 165 bigreactors:basic_turbineglass
# basic-side-glass-101-166: basic assembled turbine glass
setblock 168 101 166 bigreactors:basic_turbineglass
# basic-side-glass-101-167: basic assembled turbine glass
setblock 168 101 167 bigreactors:basic_turbineglass
# basic-side-glass-102-165: basic assembled turbine glass
setblock 168 102 165 bigreactors:basic_turbineglass
# basic-side-glass-102-166: basic assembled turbine glass
setblock 168 102 166 bigreactors:basic_turbineglass
# basic-side-glass-102-167: basic assembled turbine glass
setblock 168 102 167 bigreactors:basic_turbineglass
# basic-side-glass-103-165: basic assembled turbine glass
setblock 168 103 165 bigreactors:basic_turbineglass
# basic-side-glass-103-166: basic assembled turbine glass
setblock 168 103 166 bigreactors:basic_turbineglass
# basic-side-glass-103-167: basic assembled turbine glass
setblock 168 103 167 bigreactors:basic_turbineglass
# basic-rear-glass-165-101: basic assembled turbine glass
setblock 165 101 168 bigreactors:basic_turbineglass
# basic-rear-glass-165-102: basic assembled turbine glass
setblock 165 102 168 bigreactors:basic_turbineglass
# basic-rear-glass-165-103: basic assembled turbine glass
setblock 165 103 168 bigreactors:basic_turbineglass
# basic-rear-glass-166-101: basic assembled turbine glass
setblock 166 101 168 bigreactors:basic_turbineglass
# basic-rear-glass-166-103: basic assembled turbine glass
setblock 166 103 168 bigreactors:basic_turbineglass
# basic-rear-glass-167-101: basic assembled turbine glass
setblock 167 101 168 bigreactors:basic_turbineglass
# basic-rear-glass-167-102: basic assembled turbine glass
setblock 167 102 168 bigreactors:basic_turbineglass
# basic-rear-glass-167-103: basic assembled turbine glass
setblock 167 103 168 bigreactors:basic_turbineglass
# basic-terminal-casing: basic terminal rotor casing
setblock 166 102 168 bigreactors:basic_turbinecasing
# basic-shaft-1: basic contextual shaft section 1
setblock 166 102 165 bigreactors:basic_turbinerotorshaft
# basic-blade-1-west: basic contextual rotor blade
setblock 165 102 165 bigreactors:basic_turbinerotorblade
# basic-blade-1-east: basic contextual rotor blade
setblock 167 102 165 bigreactors:basic_turbinerotorblade
# basic-blade-1-down: basic contextual rotor blade
setblock 166 101 165 bigreactors:basic_turbinerotorblade
# basic-blade-1-up: basic contextual rotor blade
setblock 166 103 165 bigreactors:basic_turbinerotorblade
# basic-shaft-2: basic contextual shaft section 2
setblock 166 102 166 bigreactors:basic_turbinerotorshaft
# basic-blade-2-west: basic contextual rotor blade
setblock 165 102 166 bigreactors:basic_turbinerotorblade
# basic-blade-2-east: basic contextual rotor blade
setblock 167 102 166 bigreactors:basic_turbinerotorblade
# basic-blade-2-down: basic contextual rotor blade
setblock 166 101 166 bigreactors:basic_turbinerotorblade
# basic-blade-2-up: basic contextual rotor blade
setblock 166 103 166 bigreactors:basic_turbinerotorblade
# basic-shaft-3: basic contextual shaft section 3
setblock 166 102 167 bigreactors:basic_turbinerotorshaft
# basic-coil-165-101: basic ludicrite coil
setblock 165 101 167 bigreactors:ludicrite_block
# basic-coil-165-102: basic ludicrite coil
setblock 165 102 167 bigreactors:ludicrite_block
# basic-coil-165-103: basic ludicrite coil
setblock 165 103 167 bigreactors:ludicrite_block
# basic-coil-166-101: basic ludicrite coil
setblock 166 101 167 bigreactors:ludicrite_block
# basic-coil-166-103: basic ludicrite coil
setblock 166 103 167 bigreactors:ludicrite_block
# basic-coil-167-101: basic ludicrite coil
setblock 167 101 167 bigreactors:ludicrite_block
# basic-coil-167-102: basic ludicrite coil
setblock 167 102 167 bigreactors:ludicrite_block
# basic-coil-167-103: basic ludicrite coil
setblock 167 103 167 bigreactors:ludicrite_block
# basic-controller: basic assembled turbine controller
setblock 165 102 164 bigreactors:basic_turbinecontroller
# basic-bearing: basic assembled turbine rotor bearing
setblock 166 102 164 bigreactors:basic_turbinerotorbearing
# reinforced-shell-176-100-164: reinforced assembled turbine shell
setblock 176 100 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-100-165: reinforced assembled turbine shell
setblock 176 100 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-100-166: reinforced assembled turbine shell
setblock 176 100 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-100-167: reinforced assembled turbine shell
setblock 176 100 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-100-168: reinforced assembled turbine shell
setblock 176 100 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-101-164: reinforced assembled turbine shell
setblock 176 101 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-101-165: reinforced assembled turbine shell
setblock 176 101 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-101-166: reinforced assembled turbine shell
setblock 176 101 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-101-167: reinforced assembled turbine shell
setblock 176 101 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-101-168: reinforced assembled turbine shell
setblock 176 101 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-102-164: reinforced assembled turbine shell
setblock 176 102 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-102-165: reinforced assembled turbine shell
setblock 176 102 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-102-166: reinforced assembled turbine shell
setblock 176 102 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-102-167: reinforced assembled turbine shell
setblock 176 102 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-102-168: reinforced assembled turbine shell
setblock 176 102 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-103-164: reinforced assembled turbine shell
setblock 176 103 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-103-165: reinforced assembled turbine shell
setblock 176 103 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-103-166: reinforced assembled turbine shell
setblock 176 103 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-103-167: reinforced assembled turbine shell
setblock 176 103 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-103-168: reinforced assembled turbine shell
setblock 176 103 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-104-164: reinforced assembled turbine shell
setblock 176 104 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-104-165: reinforced assembled turbine shell
setblock 176 104 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-104-166: reinforced assembled turbine shell
setblock 176 104 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-104-167: reinforced assembled turbine shell
setblock 176 104 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-176-104-168: reinforced assembled turbine shell
setblock 176 104 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-100-164: reinforced assembled turbine shell
setblock 177 100 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-100-165: reinforced assembled turbine shell
setblock 177 100 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-100-166: reinforced assembled turbine shell
setblock 177 100 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-100-167: reinforced assembled turbine shell
setblock 177 100 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-100-168: reinforced assembled turbine shell
setblock 177 100 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-101-164: reinforced assembled turbine shell
setblock 177 101 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-103-164: reinforced assembled turbine shell
setblock 177 103 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-104-164: reinforced assembled turbine shell
setblock 177 104 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-177-104-168: reinforced assembled turbine shell
setblock 177 104 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-100-164: reinforced assembled turbine shell
setblock 178 100 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-100-165: reinforced assembled turbine shell
setblock 178 100 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-100-166: reinforced assembled turbine shell
setblock 178 100 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-100-167: reinforced assembled turbine shell
setblock 178 100 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-100-168: reinforced assembled turbine shell
setblock 178 100 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-101-164: reinforced assembled turbine shell
setblock 178 101 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-103-164: reinforced assembled turbine shell
setblock 178 103 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-104-164: reinforced assembled turbine shell
setblock 178 104 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-178-104-168: reinforced assembled turbine shell
setblock 178 104 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-100-164: reinforced assembled turbine shell
setblock 179 100 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-100-165: reinforced assembled turbine shell
setblock 179 100 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-100-166: reinforced assembled turbine shell
setblock 179 100 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-100-167: reinforced assembled turbine shell
setblock 179 100 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-100-168: reinforced assembled turbine shell
setblock 179 100 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-101-164: reinforced assembled turbine shell
setblock 179 101 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-102-164: reinforced assembled turbine shell
setblock 179 102 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-103-164: reinforced assembled turbine shell
setblock 179 103 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-104-164: reinforced assembled turbine shell
setblock 179 104 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-179-104-168: reinforced assembled turbine shell
setblock 179 104 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-100-164: reinforced assembled turbine shell
setblock 180 100 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-100-165: reinforced assembled turbine shell
setblock 180 100 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-100-166: reinforced assembled turbine shell
setblock 180 100 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-100-167: reinforced assembled turbine shell
setblock 180 100 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-100-168: reinforced assembled turbine shell
setblock 180 100 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-101-164: reinforced assembled turbine shell
setblock 180 101 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-101-168: reinforced assembled turbine shell
setblock 180 101 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-102-164: reinforced assembled turbine shell
setblock 180 102 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-102-168: reinforced assembled turbine shell
setblock 180 102 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-103-164: reinforced assembled turbine shell
setblock 180 103 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-103-168: reinforced assembled turbine shell
setblock 180 103 168 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-104-164: reinforced assembled turbine shell
setblock 180 104 164 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-104-165: reinforced assembled turbine shell
setblock 180 104 165 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-104-166: reinforced assembled turbine shell
setblock 180 104 166 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-104-167: reinforced assembled turbine shell
setblock 180 104 167 bigreactors:reinforced_turbinecasing
# reinforced-shell-180-104-168: reinforced assembled turbine shell
setblock 180 104 168 bigreactors:reinforced_turbinecasing
# reinforced-top-glass-177-165: reinforced assembled turbine glass
setblock 177 104 165 bigreactors:reinforced_turbineglass
# reinforced-top-glass-177-166: reinforced assembled turbine glass
setblock 177 104 166 bigreactors:reinforced_turbineglass
# reinforced-top-glass-177-167: reinforced assembled turbine glass
setblock 177 104 167 bigreactors:reinforced_turbineglass
# reinforced-top-glass-178-165: reinforced assembled turbine glass
setblock 178 104 165 bigreactors:reinforced_turbineglass
# reinforced-top-glass-178-166: reinforced assembled turbine glass
setblock 178 104 166 bigreactors:reinforced_turbineglass
# reinforced-top-glass-178-167: reinforced assembled turbine glass
setblock 178 104 167 bigreactors:reinforced_turbineglass
# reinforced-top-glass-179-165: reinforced assembled turbine glass
setblock 179 104 165 bigreactors:reinforced_turbineglass
# reinforced-top-glass-179-166: reinforced assembled turbine glass
setblock 179 104 166 bigreactors:reinforced_turbineglass
# reinforced-top-glass-179-167: reinforced assembled turbine glass
setblock 179 104 167 bigreactors:reinforced_turbineglass
# reinforced-side-glass-101-165: reinforced assembled turbine glass
setblock 180 101 165 bigreactors:reinforced_turbineglass
# reinforced-side-glass-101-166: reinforced assembled turbine glass
setblock 180 101 166 bigreactors:reinforced_turbineglass
# reinforced-side-glass-101-167: reinforced assembled turbine glass
setblock 180 101 167 bigreactors:reinforced_turbineglass
# reinforced-side-glass-102-165: reinforced assembled turbine glass
setblock 180 102 165 bigreactors:reinforced_turbineglass
# reinforced-side-glass-102-166: reinforced assembled turbine glass
setblock 180 102 166 bigreactors:reinforced_turbineglass
# reinforced-side-glass-102-167: reinforced assembled turbine glass
setblock 180 102 167 bigreactors:reinforced_turbineglass
# reinforced-side-glass-103-165: reinforced assembled turbine glass
setblock 180 103 165 bigreactors:reinforced_turbineglass
# reinforced-side-glass-103-166: reinforced assembled turbine glass
setblock 180 103 166 bigreactors:reinforced_turbineglass
# reinforced-side-glass-103-167: reinforced assembled turbine glass
setblock 180 103 167 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-177-101: reinforced assembled turbine glass
setblock 177 101 168 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-177-102: reinforced assembled turbine glass
setblock 177 102 168 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-177-103: reinforced assembled turbine glass
setblock 177 103 168 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-178-101: reinforced assembled turbine glass
setblock 178 101 168 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-178-103: reinforced assembled turbine glass
setblock 178 103 168 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-179-101: reinforced assembled turbine glass
setblock 179 101 168 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-179-102: reinforced assembled turbine glass
setblock 179 102 168 bigreactors:reinforced_turbineglass
# reinforced-rear-glass-179-103: reinforced assembled turbine glass
setblock 179 103 168 bigreactors:reinforced_turbineglass
# reinforced-terminal-casing: reinforced terminal rotor casing
setblock 178 102 168 bigreactors:reinforced_turbinecasing
# reinforced-shaft-1: reinforced contextual shaft section 1
setblock 178 102 165 bigreactors:reinforced_turbinerotorshaft
# reinforced-blade-1-west: reinforced contextual rotor blade
setblock 177 102 165 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-1-east: reinforced contextual rotor blade
setblock 179 102 165 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-1-down: reinforced contextual rotor blade
setblock 178 101 165 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-1-up: reinforced contextual rotor blade
setblock 178 103 165 bigreactors:reinforced_turbinerotorblade
# reinforced-shaft-2: reinforced contextual shaft section 2
setblock 178 102 166 bigreactors:reinforced_turbinerotorshaft
# reinforced-blade-2-west: reinforced contextual rotor blade
setblock 177 102 166 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-2-east: reinforced contextual rotor blade
setblock 179 102 166 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-2-down: reinforced contextual rotor blade
setblock 178 101 166 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-2-up: reinforced contextual rotor blade
setblock 178 103 166 bigreactors:reinforced_turbinerotorblade
# reinforced-shaft-3: reinforced contextual shaft section 3
setblock 178 102 167 bigreactors:reinforced_turbinerotorshaft
# reinforced-coil-177-101: reinforced ludicrite coil
setblock 177 101 167 bigreactors:ludicrite_block
# reinforced-coil-177-102: reinforced ludicrite coil
setblock 177 102 167 bigreactors:ludicrite_block
# reinforced-coil-177-103: reinforced ludicrite coil
setblock 177 103 167 bigreactors:ludicrite_block
# reinforced-coil-178-101: reinforced ludicrite coil
setblock 178 101 167 bigreactors:ludicrite_block
# reinforced-coil-178-103: reinforced ludicrite coil
setblock 178 103 167 bigreactors:ludicrite_block
# reinforced-coil-179-101: reinforced ludicrite coil
setblock 179 101 167 bigreactors:ludicrite_block
# reinforced-coil-179-102: reinforced ludicrite coil
setblock 179 102 167 bigreactors:ludicrite_block
# reinforced-coil-179-103: reinforced ludicrite coil
setblock 179 103 167 bigreactors:ludicrite_block
# reinforced-controller: reinforced assembled turbine controller
setblock 177 102 164 bigreactors:reinforced_turbinecontroller
# reinforced-bearing: reinforced assembled turbine rotor bearing
setblock 178 102 164 bigreactors:reinforced_turbinerotorbearing
# stock-control: stone stock rendering control
setblock 172 100 171 minecraft:stone
function bigreactors_gallery:verify
