# Generated by gallery/generate.py; do not edit.
function bigreactors_gallery:clear
# basic-bearing: basic rotor bearing control
setblock 170 102 164 bigreactors:basic_turbinerotorbearing
# basic-shaft-1: basic contextual shaft section 1
setblock 170 102 165 bigreactors:basic_turbinerotorshaft
# basic-blade-1-x--1-1: basic contextual blade span
setblock 169 102 165 bigreactors:basic_turbinerotorblade
# basic-blade-1-x--1-2: basic contextual blade span
setblock 168 102 165 bigreactors:basic_turbinerotorblade
# basic-blade-1-x-1-1: basic contextual blade span
setblock 171 102 165 bigreactors:basic_turbinerotorblade
# basic-blade-1-x-1-2: basic contextual blade span
setblock 172 102 165 bigreactors:basic_turbinerotorblade
# basic-shaft-2: basic contextual shaft section 2
setblock 170 102 166 bigreactors:basic_turbinerotorshaft
# basic-blade-2-y--1-1: basic contextual blade span
setblock 170 101 166 bigreactors:basic_turbinerotorblade
# basic-blade-2-y--1-2: basic contextual blade span
setblock 170 100 166 bigreactors:basic_turbinerotorblade
# basic-blade-2-y-1-1: basic contextual blade span
setblock 170 103 166 bigreactors:basic_turbinerotorblade
# basic-blade-2-y-1-2: basic contextual blade span
setblock 170 104 166 bigreactors:basic_turbinerotorblade
# basic-shaft-3: basic contextual shaft section 3
setblock 170 102 167 bigreactors:basic_turbinerotorshaft
# basic-blade-3-x--1-1: basic contextual blade span
setblock 169 102 167 bigreactors:basic_turbinerotorblade
# basic-blade-3-x--1-2: basic contextual blade span
setblock 168 102 167 bigreactors:basic_turbinerotorblade
# basic-blade-3-x-1-1: basic contextual blade span
setblock 171 102 167 bigreactors:basic_turbinerotorblade
# basic-blade-3-x-1-2: basic contextual blade span
setblock 172 102 167 bigreactors:basic_turbinerotorblade
# basic-blade-3-y--1-1: basic contextual blade span
setblock 170 101 167 bigreactors:basic_turbinerotorblade
# basic-blade-3-y--1-2: basic contextual blade span
setblock 170 100 167 bigreactors:basic_turbinerotorblade
# basic-blade-3-y-1-1: basic contextual blade span
setblock 170 103 167 bigreactors:basic_turbinerotorblade
# basic-blade-3-y-1-2: basic contextual blade span
setblock 170 104 167 bigreactors:basic_turbinerotorblade
# basic-shaft-4: basic contextual shaft section 4
setblock 170 102 168 bigreactors:basic_turbinerotorshaft
# basic-blade-4-y--1-1: basic contextual blade span
setblock 170 101 168 bigreactors:basic_turbinerotorblade
# basic-blade-4-y--1-2: basic contextual blade span
setblock 170 100 168 bigreactors:basic_turbinerotorblade
# basic-blade-4-y-1-1: basic contextual blade span
setblock 170 103 168 bigreactors:basic_turbinerotorblade
# basic-blade-4-y-1-2: basic contextual blade span
setblock 170 104 168 bigreactors:basic_turbinerotorblade
# reinforced-bearing: reinforced rotor bearing control
setblock 180 102 164 bigreactors:reinforced_turbinerotorbearing
# reinforced-shaft-1: reinforced contextual shaft section 1
setblock 180 102 165 bigreactors:reinforced_turbinerotorshaft
# reinforced-blade-1-x--1-1: reinforced contextual blade span
setblock 179 102 165 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-1-x--1-2: reinforced contextual blade span
setblock 178 102 165 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-1-x-1-1: reinforced contextual blade span
setblock 181 102 165 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-1-x-1-2: reinforced contextual blade span
setblock 182 102 165 bigreactors:reinforced_turbinerotorblade
# reinforced-shaft-2: reinforced contextual shaft section 2
setblock 180 102 166 bigreactors:reinforced_turbinerotorshaft
# reinforced-blade-2-y--1-1: reinforced contextual blade span
setblock 180 101 166 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-2-y--1-2: reinforced contextual blade span
setblock 180 100 166 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-2-y-1-1: reinforced contextual blade span
setblock 180 103 166 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-2-y-1-2: reinforced contextual blade span
setblock 180 104 166 bigreactors:reinforced_turbinerotorblade
# reinforced-shaft-3: reinforced contextual shaft section 3
setblock 180 102 167 bigreactors:reinforced_turbinerotorshaft
# reinforced-blade-3-x--1-1: reinforced contextual blade span
setblock 179 102 167 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-3-x--1-2: reinforced contextual blade span
setblock 178 102 167 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-3-x-1-1: reinforced contextual blade span
setblock 181 102 167 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-3-x-1-2: reinforced contextual blade span
setblock 182 102 167 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-3-y--1-1: reinforced contextual blade span
setblock 180 101 167 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-3-y--1-2: reinforced contextual blade span
setblock 180 100 167 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-3-y-1-1: reinforced contextual blade span
setblock 180 103 167 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-3-y-1-2: reinforced contextual blade span
setblock 180 104 167 bigreactors:reinforced_turbinerotorblade
# reinforced-shaft-4: reinforced contextual shaft section 4
setblock 180 102 168 bigreactors:reinforced_turbinerotorshaft
# reinforced-blade-4-y--1-1: reinforced contextual blade span
setblock 180 101 168 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-4-y--1-2: reinforced contextual blade span
setblock 180 100 168 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-4-y-1-1: reinforced contextual blade span
setblock 180 103 168 bigreactors:reinforced_turbinerotorblade
# reinforced-blade-4-y-1-2: reinforced contextual blade span
setblock 180 104 168 bigreactors:reinforced_turbinerotorblade
# stock-control: stone stock rendering control
setblock 175 100 171 minecraft:stone
function bigreactors_gallery:verify
